### ISSUE TITLE
menu alignment 

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [camelcasetechsd/testing-engine#352]
Menu looks un formated well 
![image](https://user-images.githubusercontent.com/17373050/45160532-00484500-b1ea-11e8-970e-1d78f0a423bf.png)

**Comment by MoatazAbdAlmageed** [comment]
@ahmedelbougha  I noticed that the menus is fixed in `develop` branch just add the following css 
```css
 .home4 .site-brand, .page .site-brand, .home5 .site-brand, .page-blog .site-brand {
    margin-left: 2em;
}

.home4 .main-menu > ul > li > a {
    padding: 0 10px;
}

.list1 {
    width: 72%;
}

```
